/* GENERATED by the archlet skill. */
window.ARCH = {
  config: {
    project: 'archlet',
    layers: {
      cli:      { label: 'CLI (Node)',        border: '#9db8d6', ink: '#3b6fb0' },
      viewer:   { label: 'Viewer (Browser)',  border: '#a7d0bb', ink: '#3f8f6b' },
      data:     { label: '.archlet Contract', border: '#d6c08f', ink: '#8a6d22', fill: '#faf6ec' },
      gen:      { label: 'Skill (Generator)', border: '#cbb3da', ink: '#7a4fa6' },
      ext:      { label: 'External',          border: '#cfc6b8', ink: '#6b6256', fill: '#f3f1ea' },
    },
  },

  nodes: [
    // ── CLI: the `archlet` command (bin + lib) ──────────────────────────────
    { id: 'cli', name: 'CLI', g: 'cli', brief: 'the archlet command',
      role: 'The `archlet` command — serves the map and validates the generated data files.',
      rt: 'bin/archlet.mjs' },

    { id: 'cli-entry', name: 'archlet (entry)', g: 'cli', parent: 'cli', brief: 'argv → lib/<cmd>',
      role: 'Parses argv and dynamically imports a same-named lib/<cmd>.mjs module to run it.',
      rt: 'bin/archlet.mjs', path: 'bin/archlet.mjs' },

    { id: 'cmd-view', name: 'view', g: 'cli', parent: 'cli', brief: 'serve .archlet + viewer',
      role: 'HTTP server that serves the packaged viewer plus the user’s .archlet/ data, then opens the browser.',
      rt: 'lib/view.mjs', path: 'lib/view.mjs',
      methods: [
        { name: 'run',         src: 'lib/view.mjs:19', calls: 0 },
        { name: 'openBrowser', src: 'lib/view.mjs:8',  calls: 1 },
      ] },

    { id: 'cmd-validate', name: 'validate', g: 'cli', parent: 'cli', brief: 'shape + ref-integrity check',
      role: 'Checks data.js, diffs, and the manifest against an embedded schema mini-language.',
      rt: 'lib/validate.mjs', path: 'lib/validate.mjs',
      methods: [
        { name: 'run',           src: 'lib/validate.mjs:126', calls: 0 },
        { name: 'checkFields',   src: 'lib/validate.mjs:57',  calls: 4 },
        { name: 'checkVal',      src: 'lib/validate.mjs:37',  calls: 4 },
        { name: 'loadGlobals',   src: 'lib/validate.mjs:72',  calls: 3 },
        { name: 'checkArchRefs', src: 'lib/validate.mjs:80',  calls: 1 },
        { name: 'checkDiffRefs', src: 'lib/validate.mjs:113', calls: 1 },
      ] },

    { id: 'lib-util', name: 'util', g: 'cli', parent: 'cli', brief: 'shared paths + flags',
      role: 'Shared helpers: repo / package / viewer paths and a tiny CLI flag parser.',
      rt: 'lib/util.mjs', path: 'lib/util.mjs',
      methods: [
        { name: 'flag', src: 'lib/util.mjs:9', calls: 2 },
      ] },

    // ── Viewer: the browser-side map ────────────────────────────────────────
    { id: 'viewer', name: 'Viewer', g: 'viewer', brief: 'browser-side map',
      role: 'The static viewer that renders .archlet/ into an interactive, zoomable map.',
      rt: 'viewer/index.html' },

    { id: 'viewer-shell', name: 'index.html', g: 'viewer', parent: 'viewer', brief: 'HTML shell + load order',
      role: 'HTML shell that loads d3, data.js, the diff manifest, and the engine in dependency order.',
      rt: 'viewer/index.html', path: 'viewer/index.html' },

    { id: 'viewer-engine', name: 'graph.js', g: 'viewer', parent: 'viewer', brief: 'D3 render engine',
      role: 'D3 force-layout engine: draws the node tree, edges, method-call edges, and diff overlays with expand / collapse.',
      rt: 'viewer/graph.js', path: 'viewer/graph.js',
      methods: [
        { name: 'start',        src: 'viewer/graph.js:22' },
        { name: 'draw',         src: 'viewer/graph.js:351' },
        { name: 'computeView',  src: 'viewer/graph.js:188' },
        { name: 'setFocus',     src: 'viewer/graph.js:293' },
        { name: 'tick',         src: 'viewer/graph.js:280' },
        { name: 'openInEditor', src: 'viewer/graph.js:60' },
      ] },

    { id: 'viewer-styles', name: 'styles.css', g: 'viewer', parent: 'viewer', brief: 'viewer styling',
      role: 'Stylesheet for the viewer chrome, cards, links, method dots, and diff markers.',
      rt: 'viewer/styles.css', path: 'viewer/styles.css' },

    // ── The shared contract: generated .archlet/ data ───────────────────────
    { id: 'data-contract', name: '.archlet/ data', g: 'data', brief: 'window.ARCH source of truth',
      role: 'Generated data.js (window.ARCH) plus diff overlays and manifest — the single contract the viewer reads and validate checks.',
      rt: '.archlet/data.js', path: '.archlet' },

    // ── The skill: what generates the contract ──────────────────────────────
    { id: 'skill', name: 'SKILL.md', g: 'gen', brief: 'agent map generator',
      role: 'Instructions a coding agent follows to scan the repo and write .archlet/data.js (MAP) or diff overlays (DIFF).',
      rt: 'SKILL.md', path: 'SKILL.md' },

    // ── External ────────────────────────────────────────────────────────────
    { id: 'd3', name: 'D3 v7', g: 'ext', brief: 'force layout + SVG',
      role: 'D3 library loaded from a CDN; supplies the force simulation and SVG selections the engine drives.',
      rt: 'cdn.jsdelivr.net/npm/d3@7' },

    { id: 'codegraph', name: 'codegraph', g: 'ext', brief: 'import + call graph',
      role: 'npx tool the skill runs to extract routes and the import / call graph into .codegraph/codegraph.db.',
      rt: '@colbymchenry/codegraph' },

    { id: 'madge', name: 'madge', g: 'ext', brief: 'JS/TS import graph',
      role: 'npx tool the skill runs to extract the file→file import graph for JS / TS source roots.',
      rt: 'madge' },
  ],

  edges: [
    // CLI dispatch + internal imports
    { s: 'cli-entry', t: 'cmd-view',     k: 'dispatch', l: 'view',     src: 'bin/archlet.mjs:18', method: 'manual' },
    { s: 'cli-entry', t: 'cmd-validate', k: 'dispatch', l: 'validate', src: 'bin/archlet.mjs:18', method: 'manual' },
    { s: 'cmd-view',  t: 'lib-util',     k: 'import',                  src: 'lib/view.mjs:5',     method: 'mechanical' },

    // CLI → the served / validated artifacts
    { s: 'cmd-view',     t: 'viewer-shell',  k: 'serves',    src: 'lib/view.mjs:28',     method: 'manual' },
    { s: 'cmd-view',     t: 'data-contract', k: 'serves',    l: 'data.js + diffs', src: 'lib/view.mjs:42', method: 'manual' },
    { s: 'cmd-validate', t: 'data-contract', k: 'validates', src: 'lib/validate.mjs:142', method: 'manual' },

    // Viewer load chain (index.html script tags) + runtime reads
    { s: 'viewer-shell',  t: 'd3',            k: 'loads',                   src: 'viewer/index.html:30', method: 'manual' },
    { s: 'viewer-shell',  t: 'data-contract', k: 'loads', l: 'window.ARCH', src: 'viewer/index.html:31', method: 'manual' },
    { s: 'viewer-shell',  t: 'viewer-engine', k: 'loads',                   src: 'viewer/index.html:33', method: 'manual' },
    { s: 'viewer-shell',  t: 'viewer-styles', k: 'loads',                   src: 'viewer/index.html:7',  method: 'manual' },
    { s: 'viewer-engine', t: 'data-contract', k: 'reads', l: 'window.ARCH', src: 'viewer/graph.js:23',   method: 'manual' },
    { s: 'viewer-engine', t: 'd3',            k: 'uses',                    src: 'viewer/graph.js:12',   method: 'manual' },

    // Generation pipeline (the skill drives everything)
    { s: 'skill', t: 'data-contract', k: 'writes', l: 'data.js',             src: 'SKILL.md:26', method: 'manual' },
    { s: 'skill', t: 'codegraph',     k: 'runs',                            src: 'SKILL.md:56', method: 'manual' },
    { s: 'skill', t: 'madge',         k: 'runs',                            src: 'SKILL.md:61', method: 'manual' },
    { s: 'skill', t: 'cli-entry',     k: 'runs',   l: 'archlet view/validate', src: 'SKILL.md:88', method: 'manual' },
  ],

  methodEdges: [
    // the one cross-file call the call graph captured: view.run() reads flags via util.flag()
    { sNode: 'cmd-view', sMethod: 'run', tNode: 'lib-util', tMethod: 'flag', src: 'lib/view.mjs:21' },
  ],
};
