"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000
add_newline = true

format = """
[](color_green)\
$username\
[](fg:color_green bg:color_orange)\
$directory\
[](fg:color_orange bg:color_blue)\
$git_branch\
$git_status\
[ ](fg:color_blue)\
$character"""

right_format = """
$cmd_duration\
$all\
$time"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[line_break]
disabled = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[time]
disabled = false

[username]
disabled = true
show_always = true
style_user = "bold fg:color_fg0 bg:color_green"
style_root = "bold fg:color_fg0 bg:color_red"
format = '[$user ]($style)'

[directory]
style = "bold fg:color_fg0 bg:color_orange"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
truncation_length = 26
style = "bg:color_blue"
format = '[[ $symbol $branch ](bold fg:color_fg0 bg:color_blue)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](bold fg:color_fg0 bg:color_aqua)]($style)'

[aws]
disabled = true
